modLoader="javafml"
loaderVersion="[32,)"

[[mods]]
modId="dogmode"
version="${file.jarVersion}"
displayName="Dogmode"
displayURL="http://www.floozutter.site/"
logoFile="examplemod.png"
credits="Hello, world!"
authors="Floozutter"
description='''
A Minecraft cheat client for dogs!
'''